name: Build images
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.query.outputs.boards }}
      suites: ${{ steps.query.outputs.suites }}
      flavors: ${{ steps.query.outputs.flavors }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "boards=$(./rbuild json boards)" >> $GITHUB_OUTPUT
          echo "suites=$(./rbuild json suites)" >> $GITHUB_OUTPUT
          echo "flavors=$(./rbuild json flavors)" >> $GITHUB_OUTPUT

  build-rootfs:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        boards: [ rootfs ]
        suites: [ bullseye ]
        flavors: [ cli ]
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: dharquissandas/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          kernel:  "../kernel/linux-image-5.10.110-99-rockchip_5.10.110-99-rockchip_arm64.deb"
          test-repo: true
          artifacts: true

  build-images:
    needs: [ query, build-rootfs ]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        boards: [ rock-5a ]
        suites: [ bullseye ]
        flavors: [ cli ]
        exclude:
          - boards: rootfs
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: dharquissandas/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          kernel:  "../kernel/linux-image-5.10.110-99-rockchip_5.10.110-99-rockchip_arm64.deb"
          test-repo: true
          artifacts: true
          prebuilt-rootfs: true